name: Build and Test Stock Agent

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test Configuration (Secrets Check)
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      run: |
        # Simple script to verify keys are injected correctly
        python -c "import config; print('Keys loaded successfully') if config.ALPHA_VANTAGE_API_KEY else exit(1)"

    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag stock-market-agent:latest